development:
  adapter: postgresql
  encoding: utf8
  database: investingmaths_dev
  pool: 5
  username: investingmaths
  password: password

test:
  adapter: postgresql
  encoding: utf8
  database: investingmaths_test
  pool: 5
  username: investingmaths
  password: password
